version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-nextsharp
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: nextsharp-seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    restart: unless-stopped

  papercut-smtp:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut-smtp
    ports:
      - "8080:80"
      - "25:25"
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: NextSharp-MySql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3307:3306" 
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: NextSharp-Postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5431:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

# rabbitmq:
#   image: rabbitmq:3.8-management-alpine
#   container_name: nextsharp-rabbit
#   hostname: my-rabbit
#   environment:
#     RABBITMQ_DEFAULT_USER: user
#     RABBITMQ_DEFAULT_PASS: password
#   ports:
#     - "5672:5672"
#     - "15672:15672"
#   restart: unless-stopped