version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-nextsharp
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  # rabbitmq:
  #   image: rabbitmq:3.8-management-alpine
  #   container_name: nextsharp-rabbit
  #   hostname: my-rabbit
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: nextsharp-seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    restart: unless-stopped

  papercut-smtp:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut-smtp
    ports:
      - "8080:80"
      - "25:25"
    restart: unless-stopped